/**
* \author RODARIE Dimitri, VERSAEVEL Romain, FLORES Isabelle
*/
#define TAILLE_FENETRE 700
#define TILE_LARGEUR  16
#define TILE_HAUTEUR 16
#define CARTE_HAUTEUR 20
#define CARTE_LARGEUR 20
#define NBR_HERO 1

#define TAILLE_MAX_FICHIER 800
#define TAILLE_MAX 22
#define NB_DEPLACEMENTS 5
#define CHAMP_DE_VISION 30;

